-- ---------------------------------------------------------------------
-- The question bank, one row per question.
--
-- It used to live in quiz_quizzes: one row per question type (several for
-- the big types), each holding thousands of items in one jsonb array.
-- By September 2026 that was tens of MB, so every small import rewrote
-- megabytes, and reading the rows hit the statement timeout and took the
-- builder down with it. Here each item is its own row: `q` is the whole
-- item, and the columns beside it are the few things the bank counts or
-- filters on. `pos` keeps the old order (oldest first).
--
-- The old quiz_quizzes bank rows are left in place, untouched, as a
-- backup; nothing reads them any more.
-- ---------------------------------------------------------------------

create table if not exists quiz_bank (
  id          text primary key,                     -- the item's own id (q_xxxxxxxx)
  type        text not null,                        -- which bank it is in: choice, text, pin, catchphrase...
  category    text not null default '',             -- the topic it was written for
  difficulty  text not null default '',             -- easy / medium / hard, or blank
  used        boolean not null default false,       -- true once it has gone into a quiz (or been rejected)
  pos         bigint generated by default as identity,
  q           jsonb not null,
  updated_at  timestamptz not null default now()
);
create index if not exists quiz_bank_type_pos on quiz_bank (type, pos);
alter table quiz_bank enable row level security;

-- The counts behind the builder's bank panel, so it never has to read the items themselves.
create or replace view quiz_bank_counts with (security_invoker = true) as
  select type, category, difficulty, used, count(*)::int as n
  from quiz_bank group by type, category, difficulty, used;
revoke all on quiz_bank_counts from anon, authenticated;

-- Copy everything across from the old rows, in their old order.
insert into quiz_bank (id, type, category, difficulty, used, q)
select e.elem->>'id',
       r.settings->>'type',
       coalesce(e.elem->>'category', ''),
       coalesce(e.elem->>'difficulty', ''),
       coalesce(jsonb_typeof(e.elem->'used') not in ('null', 'boolean') or (e.elem->'used') = 'true'::jsonb, false),
       e.elem
from quiz_quizzes r
cross join lateral jsonb_array_elements(r.questions) with ordinality as e(elem, ord)
where r.settings->>'bank' = 'true'
order by r.settings->>'type', coalesce((r.settings->>'part')::int, 0), e.ord
on conflict (id) do nothing;
